# Note: Requires docker 1.10.0+ and docker-compose 1.6.0+.
version: "2"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
